#pragma config(Sensor, dgtl1,  ledGreen,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledYellow,   sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  ledRed,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  armSwitch,   sensorTouch)
#pragma config(Sensor, dgtl12, autonJumper, sensorTouch)
#pragma config(Motor,  port2,  motorA,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,  motorB,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  motorC,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,  motorD,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,  lockServo,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,  armRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,  armLeft,     tmotorVex393_MC29, openLoop)

#pragma platform(VEX2)
#pragma competitionControl(Competition)
