#pragma config(Motor,  port4,  motorA,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,  motorB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,  motorC,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,  motorD,        tmotorVex393_MC29, openLoop)
#pragma config(Sensor, dgtl9,  ledGreen,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  ledRed,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  ledYellow,   sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  armSwitch,   sensorTouch)
#pragma config(Sensor, dgtl12, autonJumper, sensorTouch)
#pragma config(Motor,  port7,  lockServo,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,  armRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,  armLeft,     tmotorVex393_MC29, openLoop)

#pragma platform(VEX2)
#pragma competitionControl(Competition)
