#pragma config(Sensor, dgtl2,  ledRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  ledGreen,       sensorLEDtoVCC)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           rightMid,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           leftMid,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           leftBack,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           armRight,      tmotorNone, openLoop)
#pragma config(Motor,  port7,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           sideMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftFront,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool isFlipped = false;					// Toggles front side
bool slowMode = false;
int slowModePercent = 4;
int slowModePercentSide = 3;
int jsThreshold = 25; 					// Minimum amount for joystick to move

// Flip sides
void testBtn8D() {
  while (vexRT[Btn8D]) {
    wait1Msec(250);
    isFlipped = !isFlipped;
    if (isFlipped) { SensorValue[ledRed] = 1; } else { SensorValue[ledRed] = 0;	}
  }
}

// Toggle slowMode
void testBtn8R() {
  while (vexRT[Btn8R]) {
    wait1Msec(250);
    slowMode = !slowMode;
    if (slowMode) { SensorValue[ledGreen] = 1; } else { SensorValue[ledGreen] = 0;	}
  }
}

void movementNorm() {
  // Joysticks
  if (vexRT[Ch3] <= -jsThreshold || vexRT[Ch3] >= jsThreshold) {
    if (!slowMode) {motor[leftFront] = vexRT[Ch3]; } else {	motor[leftFront] = vexRT[Ch3] / slowModePercent; }
    } else {
    motor[leftFront] = 0;
  }

  if (vexRT[Ch2] <= -jsThreshold || vexRT[Ch2] >= jsThreshold) {
    if (!slowMode) {motor[rightFront] = -vexRT[Ch2]; } else {	motor[rightFront] = -vexRT[Ch2] / slowModePercent; }
    } else {
    motor[rightFront] = 0;
  }

  // Side Movement
  if (!slowMode) {
    while(vexRT[Btn6D]) { motor[sideMotor] = -127; }
    while(vexRT[Btn5D]) { motor[sideMotor] = 127; }
  } else {
    while(vexRT[Btn6D]) { motor[sideMotor] = -127 / slowModePercentSide; }
    while(vexRT[Btn5D]) { motor[sideMotor] = 127 / slowModePercentSide; }
  }
  motor[sideMotor] = 0;
}

void movementFlip() {
  // Joysticks
  if (vexRT[Ch3] <= -jsThreshold || vexRT[Ch3] >= jsThreshold) {
    if (!slowMode) {motor[rightFront] = vexRT[Ch3]; } else {	motor[rightFront] = vexRT[Ch3] / slowModePercent; }
  } else {
    motor[rightFront] = 0;
  }

  if (vexRT[Ch2] <= -jsThreshold || vexRT[Ch2] >= jsThreshold) {
    if (!slowMode) {motor[leftFront] = -vexRT[Ch2]; } else {	motor[leftFront] = -vexRT[Ch2] / slowModePercent; }
  } else {
    motor[leftFront] = 0;
  }

  // Side Movement
  if (!slowMode) {
    while(vexRT[Btn6D]) { motor[sideMotor] = 127; }
    while(vexRT[Btn5D]) { motor[sideMotor] = -127; }
  } else {
    while(vexRT[Btn6D]) { motor[sideMotor] = 127 / slowModePercentSide; }
    while(vexRT[Btn5D]) { motor[sideMotor] = -127 / slowModePercentSide; }
  }
  motor[sideMotor] = 0;
}

void highHang() {
  while(vexRT[Btn7U]) {
    motor[armLeft] = 127;
    motor[armRight] = -127;
  }

  while(vexRT[Btn7D]) {
    motor[armLeft] = -127;
    motor[armRight] = 127;
  }

  motor[armLeft] = 0;
  motor[armRight] = 0;
}


task main() {
	//Slave Motors
	slaveMotor(leftBack, leftFront);
	slaveMotor(leftMid, leftFront);

	slaveMotor(rightBack, rightFront);
	slaveMotor(rightMid, rightFront);

  SensorValue[ledRed] = 0;
  SensorValue[ledGreen] = 0;

	while (true) {
	  testBtn8D();
    testBtn8R();
		if (isFlipped) { movementNorm(); } else { movementFlip(); }
		highHang();
	}
}
