#pragma config(Sensor, dgtl2,  ledRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  ledGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  armSwitch,      sensorTouch)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           rightMid,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           leftMid,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           leftBack,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           armRight,      tmotorNone, openLoop)
#pragma config(Motor,  port7,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           sideMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftFront,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool isFlipped = false;					// Toggles front side
bool slowMode = false;
int slowModePercent = 4;
int slowModePercentSide = 3;
int jsThreshold = 25; 					// Minimum amount for joystick to move

// SECTION: Movement Functions

void mvtForwardLeft(short speed) {
  if (slowMode) { speed = speed / slowModePercent; }

  if (!isFlipped) {
    motor[leftFront] = -speed;
  } else {
    motor[rightFront] = -speed;
  }
}

void mvtForwardRight(short speed) {
  if (slowMode) { speed = speed / slowModePercent; }

  if (!isFlipped) {
    motor[rightFront] = speed;
  } else {
    motor[leftFront] = speed;
  }
}

void mvtSide(short speed) {
  if (isFlipped) { speed = -speed; }
  if (slowMode) { speed = speed / slowModePercentSide; }
  motor[sideMotor] = speed;
}

void mvtHighHang(short speed) {
	if (speed < 0 && SensorValue(armSwitch) != 0) {
		motor[armLeft] = 0;
		motor[armRight] = 0;
	} else {
		motor[armLeft] = speed;
  	motor[armRight] = -speed;
  }
}

// SECTION: Controller Functions

// Flip sides
void testBtn8D() {
  while (vexRT[Btn8D]) {
    wait1Msec(250);
    isFlipped = !isFlipped;
    if (isFlipped) { SensorValue[ledRed] = 1; } else { SensorValue[ledRed] = 0;	}
  }
}

// Toggle slowMode
void testBtn8R() {
  while (vexRT[Btn8R]) {
    wait1Msec(250);
    slowMode = !slowMode;
    if (slowMode) { SensorValue[ledGreen] = 1; } else { SensorValue[ledGreen] = 0;	}
  }
}

void testJoysticks() {
  // Joysticks
  if (vexRT[Ch3] <= -jsThreshold || vexRT[Ch3] >= jsThreshold) {
    mvtForwardRight(vexRT[Ch3]);
  } else {
    mvtForwardRight(0);
  }

  if (vexRT[Ch2] <= -jsThreshold || vexRT[Ch2] >= jsThreshold) {
    mvtForwardLeft(vexRT[Ch2]);
  } else {
    mvtForwardLeft(0);
  }
}

void testSideMovement() {
  while(vexRT[Btn6D]) { mvtSide(127); }
  while(vexRT[Btn5D]) { mvtSide(-127); }
  mvtSide(0);
}

void testHighHang() {
  while(vexRT[Btn7U]) { mvtHighHang(127); }
  while(vexRT[Btn7D]) { mvtHighHang(-127); }
  mvtHighHang(0);
}

task main() {
	//Slave Motors
	slaveMotor(leftBack, leftFront);
	slaveMotor(leftMid, leftFront);

	slaveMotor(rightBack, rightFront);
	slaveMotor(rightMid, rightFront);

  SensorValue[ledRed] = 0;
  SensorValue[ledGreen] = 0;

	while (true) {
	  testBtn8D();
    testBtn8R();
		testJoysticks();
		testSideMovement();
		testHighHang();
	}
}
