#pragma config(Sensor, dgtl1,  sonarFront,     sensorSONAR_inch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		writeDebugStreamLine("Sensor is at %i", SensorValue(sonarFront));
		wait1Msec(1000);
	}
}
